// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYBbLq_yrEJ0qJ2LPJspbmsaWCSO6BU68',
    appId: '1:846232745215:web:b15bda4a599cd7c0f588ca',
    messagingSenderId: '846232745215',
    projectId: 'autocar-33353',
    authDomain: 'autocar-33353.firebaseapp.com',
    storageBucket: 'autocar-33353.firebasestorage.app',
    measurementId: 'G-4Z87D7QQVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP-78m7CG587zHj0EpZrHLc-CTBz73jdM',
    appId: '1:846232745215:android:65f2342cf01b73e0f588ca',
    messagingSenderId: '846232745215',
    projectId: 'autocar-33353',
    storageBucket: 'autocar-33353.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZbHmDLofMbcHX1N0q18nP-122lHh2NzE',
    appId: '1:846232745215:ios:504976c0f68c064cf588ca',
    messagingSenderId: '846232745215',
    projectId: 'autocar-33353',
    storageBucket: 'autocar-33353.firebasestorage.app',
    iosClientId: '846232745215-385dfgr12735nu9qkh38qaamesvpiiq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZbHmDLofMbcHX1N0q18nP-122lHh2NzE',
    appId: '1:846232745215:ios:504976c0f68c064cf588ca',
    messagingSenderId: '846232745215',
    projectId: 'autocar-33353',
    storageBucket: 'autocar-33353.firebasestorage.app',
    iosClientId: '846232745215-385dfgr12735nu9qkh38qaamesvpiiq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYBbLq_yrEJ0qJ2LPJspbmsaWCSO6BU68',
    appId: '1:846232745215:web:85d3084fb0536916f588ca',
    messagingSenderId: '846232745215',
    projectId: 'autocar-33353',
    authDomain: 'autocar-33353.firebaseapp.com',
    storageBucket: 'autocar-33353.firebasestorage.app',
    measurementId: 'G-V2DP10LQ2D',
  );
}
